### ISSUE TITLE
Speaker diarization in 1.2.0+ does not work

### ISSUE THREAD

**Issue by stohrendorf** [DanRuta/xva-trainer#6]
UI error message:
```
ERROR:Traceback (most recent call last):
  File "server.py", line 200, in websocket_handler
  File "python\make_srt\model.py", line 91, in make_srt
KeyError: 'diarization'
```

server.log of version 1.2.0
```
Traceback (most recent call last):
  File "python\models_manager.py", line 37, in init_model
  File "python\speaker_diarization\model.py", line 26, in __init__
  File "python\speaker_diarization\model.py", line 129, in load_model
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pyannote\audio\features\__init__.py", line 33, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pyannote\audio\features\base.py", line 38, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pyannote\database\__init__.py", line 37, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pyannote\database\database.py", line 31, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pyannote\database\util.py", line 32, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pandas\__init__.py", line 22, in <module>
    from pandas.compat import (
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pandas\compat\__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pandas\compat\numpy\__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pandas\util\__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pandas\util\_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pandas\_libs\__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas\_libs\interval.pyx", line 1, in init pandas._libs.interval
  File "pandas\_libs\hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas\_libs\missing.pyx", line 1, in init pandas._libs.missing
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pandas\_libs\tslibs\__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas\_libs\tslibs\conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
ModuleNotFoundError: No module named 'pandas._libs.tslibs.base'
```

server.log of version 1.2.1
```
Traceback (most recent call last):
  File "python\models_manager.py", line 37, in init_model
  File "python\speaker_diarization\model.py", line 26, in __init__
  File "python\speaker_diarization\model.py", line 129, in load_model
ImportError: cannot import name 'Pretrained' from 'pyannote.audio.features' (C:\Program Files (x86)\Steam\steamapps\common\xVATrainer\resources\app\cpython_gpu\pyannote\audio\features\__init__.pyc)
```

**Comment by DanRuta** [comment]
This used to work (and it still does in the development version), but since re-building the dependencies environment, pyinstaller no longer likes pyannote (I fixed the pandas issue). I'll play around with this more

**Comment by stohrendorf** [comment]
Thank you for looking into this.

**Comment by s-ilent** [comment]
This also seems to affect speaker similarity search and speaker cluster similarity search.
